rpg_tracker/accounts/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('fichas', views.fichas, name='fichas'),
    path('user/<int:pk>', views.user_infos, name='user-info')
]

rpg_tracker/coc/urls.py
from django.urls import path
from . import views

app_name = 'coc'
urlpatterns = [
    path('ficha/<int:pk>', views.ficha, name='ficha'),
    path('skills', views.skill_list, name='skill_list'),
    path('skills/<int:pk>', views.skill_detail, name='skill_detail'),
    path('ocupations', views.ocupation_list, name='ocupation_list'),
]

rpg_tracker/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
]

rpg_tracker/hp/urls.py
from django.urls import path
from . import views

app_name = 'hp'
urlpatterns = [
    path('ficha/<int:pk>', views.ficha, name='ficha'),
    path('ficha/<int:pk>/folio-universitas', views.folio_universitas_ficha, name="folio_universitas_ficha"),
    path('folio-universitas', views.folio_universitas, name="folio_universitas"),
    path('folio-universitas/<int:pk>/cartas', views.folio_universitas_cartas, name="folio_universitas_cartas")
]

rpg_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rpg_tracker.core.urls', namespace='core')),
    path('conta/', include('rpg_tracker.accounts.urls', namespace='accounts')),
    path('coc/', include('rpg_tracker.coc.urls', namespace='coc')),
    path('hp/', include('rpg_tracker.hp.urls', namespace='hp')),
    #path('dnd/', include('rpg_tracker.dnd.urls', namespace='dnd')),
    path('admin/', admin.site.urls),
    path('api/', include('rpg_tracker.api.urls', namespace='api')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

rpg_tracker/core/models.py
import os
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db import models
from polymorphic.models import PolymorphicModel
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from hbcommons.models import UsuarioAbstract as User, AbstractBaseModel

# Create your models here.
# TODO finalizar permissão de menus
class MenuItems(AbstractBaseModel):
    title = models.CharField(verbose_name='Título', null=False, blank=False, max_length=50)
    path = models.CharField(verbose_name='Caminho do menu', null=True, blank=True, max_length=50, help_text='Python/Django style')
    parent = models.ForeignKey(to='self', related_name='childs', blank=True, null=True, verbose_name='Item pai', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'item de menu'
        verbose_name_plural  = 'itens de menu'

class MenuPerms(AbstractBaseModel):
    name = models.CharField(verbose_name='Nome', max_length=50, null=False, blank=False)
    items_permited = models.ManyToManyField(to=MenuItems, verbose_name='Itens liberados', blank=True, related_name='menu_perms')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'grupo de permissao de menu'
        verbose_name_plural  = 'grupos de permissões de menu'

class Usuario(User):
    permissions = models.ManyToManyField(to=MenuPerms, verbose_name='Permissões', blank=True, related_name='permissions_groups')
    def get_menuitens_perm(self):
        perms = []
        for p in self.permissions.all():
            for mi in p.items_permited.all():
                if mi.parent is None:
                    perms.append(self.return_menuitens_child_as_dict(mi))
        return perms

    def return_menuitens_child_as_dict(self, menuitem):
        childs = [self.return_menuitens_child_as_dict(c) for c in menuitem.childs.all()]
        return {str(menuitem.pk):{"title":menuitem.title,"path":menuitem.path, "childs" : childs}}

    def get_mesas_iniciadas(self):
        ret = []
        for x in self.fichas.all():
            if x.mesa and x.mesa.open_session:
                ret.append(x.mesa)
        return ret

    def is_mestre(self):
        return MesaBase.objects.filter(mestre=self).count() > 0

    class Meta:
        verbose_name = 'usuário'
        verbose_name_plural = 'usuários'

class MesaBase(AbstractBaseModel, PolymorphicModel):
    name = models.CharField(verbose_name='Nome da mesa', null=False, blank=False, max_length=50)
    open_session = models.BooleanField(verbose_name='Sessão aberta', default=False, null=False, blank=False)
    mestre = models.ForeignKey(to=Usuario, on_delete=models.RESTRICT, verbose_name='Mestre', related_name='mesas_mestradas', blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.open_session:
            for x in self.fichas_mesa.all():
                x.in_session = False
                x.save()
            self.mestre.in_session = False
            self.mestre.save()
        layer = get_channel_layer()
        for x in self.fichas_mesa.all():
            g_name = 'sessions_%s' % x.jogador.pk
            static_banner = ''
            alter = ''
            if self.get_content_type() == 'hp':
                static_banner = 'img/banners/hp.png'
                alter = "Harry Potter (Broomstix)"
            elif self.get_content_type() == 'coc':
                static_banner = 'img/banners/cthulhu.jpg'
                alter = "Call of Cthulhu (7e)"
            async_to_sync(layer.group_send)(
                g_name,
                {
                    'type': 'open_close_session',
                    'action': 'OPEN_SESSION' if self.open_session else 'CLOSE_SESSION',
                    'session_id': self.pk,
                    'session_name' : self.name,
                    'header' : {
                        'img' : os.path.join(settings.STATIC_URL, static_banner),
                        'alt' : alter
                    },
                    'link' : "#"
                }
            )
        super().save(*args, **kwargs)

    def is_mestre(self, user):
        return self.mestre == user

    def is_player(self, user):
        return self.fichas_mesa.filter(jogador=user).count() > 0

    def get_content_type(self):
        return ContentType.objects.get_for_id(self.polymorphic_ctype_id).app_label

    def __str__(self):
        return '{0} ({1}){2}'.format(self.name, self.get_content_type().upper(), ' - Aberta' if self.open_session else '')

class FichaBase(AbstractBaseModel, PolymorphicModel):
    nome_personagem = models.CharField(verbose_name='Nome do personagem', null=False, blank=False, max_length=50)
    jogador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='fichas')
    mesa = models.ForeignKey(to=MesaBase, on_delete=models.RESTRICT, related_name='fichas_mesa', verbose_name='Mesa', null=True, blank=True)
    in_session = models.BooleanField("Está online na sessão", default=False, null=False, blank=False)

    def get_content_type(self):
        return ContentType.objects.get_for_id(self.polymorphic_ctype_id).app_label

rpg_tracker/core/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'nickname']

rpg_tracker/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'index.html')

rpg_tracker/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .dropdown-submenu {
            position: relative;
        }

        .dropdown-submenu a::after {
            transform: rotate(-90deg);
            position: absolute;
            right: 6px;
            top: .8em;
        }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-left: .1rem;
            margin-right: .1rem;
        }

        .range-wrap {
            position: relative;
            margin: 0 auto 3rem;
        }

        .range {
            width: 100%;
        }

        .bubble {
            background: red;
            color: white;
            padding: 4px 12px;
            position: absolute;
            border-radius: 4px;
            left: 50%;
            transform: translateX(-50%);
        }
        
        .bubble::after {
            content: "";
            position: absolute;
            width: 2px;
            height: 2px;
            background: red;
            top: -1px;
            left: 50%;
        }

        thead.thead-dark a {
            color: white;
            text-decoration: none;
        }
    </style>
    {% block style %}
    {% endblock style %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/146fe99a3a.js" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.dropdown-menu a.dropdown-toggle').on('click', function(e) {
            if (!$(this).next().hasClass('show')) {
                $(this).parents('.dropdown-menu').first().find('.show').removeClass('show');
            }
            var $subMenu = $(this).next('.dropdown-menu');
            $subMenu.toggleClass('show');

            $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function(e) {
                $('.dropdown-submenu .show').removeClass('show');
            });

            return false;
            });
        });    
    </script>
    {% block js %}
    {% endblock js %}
    <title>RPGTracker</title>
</head>
<body class="d-flex flex-column h-100">
    <main role="main" class="flex-shrink-0">
        {% include 'navbar.html' %}
        <div class="alert alert-info m-4" role="alert">
            <h4 class="alert-heading">O RPGTracker está de cara nova!</h4>
            <p>Atualizamos nossos serviços para oferecer uma dinâmica melhor para a sua jogatina</p>
            <hr>
            <p class="mb-0"><a class="alert-link" href="https://rpgtracker.herokuapp.com/">Dê uma olhada!</a></p>
        </div>
        {% block body %}  
        {% endblock body %}
    </main>
    <footer class="footer mt-auto py-3 text-center text-white bg-dark">
        Developed by
        <a href="https://twitter.com/mischievousG0d" class="text-white">@HannaBananna</a>
    </footer>
</body>
</html>

rpg_tracker/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block js %}
{{ user.pk|json_script:"userPK" }}
<script type="text/javascript">
    $(document).ready(function(){
        var userPK = JSON.parse(document.getElementById('userPK').textContent);
        var ws_scheme = window.location.protocol == "https:" ? "wss:" : "ws:";
        if(userPK !== undefined && userPK !== null) {
            const chatSocket = new WebSocket(
                ws_scheme
                + window.location.host
                + '/ws/'
                + userPK
                + '/mesas'
            );

            chatSocket.onmessage = function(e) {
                const data = JSON.parse(e.data);
                let session_div = $("#sessions");
                let no_sess_mess = $("#no-session-init");
                if(data.action == "OPEN_SESSION") {
                    if(no_sess_mess.length > 0) {
                        no_sess_mess.remove();
                    }
                    if(session_div.length == 0) {
                        $("#initial-message").after("<div id='sessions' class='d-flex flex-sm-column flex-row flex-wrap align-content-around'><div class='mx-auto'><h1 class='display-4'>Mesas iniciadas</h1></div></div>");
                        session_div = $("#sessions");
                    }
                    session_div.append("<div id='session_"+data.session_id+"' class='card'><img class='card-img-top' src="+
                        data.header.img+" alt="+data.header.alt+">"+
                        "<div class='card-body'><p class='card-text'>"+
                            data.session_name+
                        "</p><a href="+data.link+" class='stretched-link'></a>");
                } else {
                    if(session_div !== undefined) { 
                        if(session_div.children().length > 1){
                            session_div.children("#session_"+data.session_id).remove()
                        }
                        if(session_div.children().length == 1) {
                            session_div.remove();
                            $("#initial-message").children(".container").append("<p class='lead' id='no-session-init'>Nenhuma mesa iniciada :c</p>");
                        }
                    }
                }
            };

            chatSocket.onclose = function(e) {
                console.error('Chat socket closed unexpectedly');
            };
        }
    });
</script>
{% endblock js %}

{% block body %}
<div class="container">
    {% if user.is_authenticated %}
    <div class="jumbotron jumbotron-fluid bg-transparent" id="initial-message">
        <div class="container">
            <h1 class="display-3">Hello there, {{ user.nickname|default_if_none:"Anon" }}</h1>
            {% if not user.get_mesas_iniciadas %}
                <p class="lead" id="no-session-init">Nenhuma mesa iniciada :c</p>
            {% endif %}
        </div>
    </div>
    {% for mesa in user.get_mesas_iniciadas %}
        {% if forloop.first %}
            <div id='sessions' class="d-flex flex-sm-row flex-column flex-wrap align-content-around">
                <div class="mx-auto"><h1 class="display-4">Mesas iniciadas</h1></div>
        {% endif %}
                <div id="session_{{ mesa.pk }}" class="card">
                    {% if mesa.get_content_type == "dnd" %}
                        <div class="card-header"><h5 class="card-title">D&D 5e</h5></div>
                    {% elif mesa.get_content_type == "coc" %}
                        <img class="card-img-top" src="{% static 'img/banners/cthulhu.jpg' %}" alt="Call of Cthulhu (7e)">
                    {% elif mesa.get_content_type == "hp" %}
                        <img class="card-img-top" src="{% static 'img/banners/hp.png' %}" alt="Harry Potter (Broomstix)">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">
                            {{ mesa.name }}
                        </p>
                        <a href="#" class="stretched-link"></a>
                    </div>
                </div>
        {% if forloop.last %}
            </div>
        {% endif %}
    {% empty %}
    {% endfor %}
    {% else %}
    <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
            <h1 class="display-3">Change you way of play</h1>
            <p class="lead">Start using RPGTracker now</p>
        </div>
    </div>
    {% endif %}
</div>
{% endblock body %}

rpg_tracker/core/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <div class="text-center mx-auto align-items-center">
        <i class="fa fa-users fa-5x text-white mt-3 bg-primary rounded-circle p-4" aria-hidden="true"></i>
        {% if form.errors %}
            <div class="mt-2 mx-2 p-3 rounded-pill alert alert-danger">
                <h5>Usuário/senha incorretos!</h5>
            </div>
        {% endif %}
        <form method='POST' class="p-4">
            {% csrf_token %}
            {% for f in form %}
                <div class="form-row form-group d-flex align-items-center text-center">
                    <div class="col-md-6 col-10 mx-auto input-group">
                        <span class="input-group-prepend">
                            <div class="input-group-text bg-white pl4 pr-3 pill-left">
                                {% if f.label == 'Email' %}
                                    <i class="fa fa-at ml-2" aria-hidden="true"> <span class="sr-only">(Email)</span> </i>
                                {% else %}
                                    <i class="fa fa-lock ml-2" aria-hidden="true"> <span class="sr-only">(Senha)</span> </i>
                                {% endif %}
                            </div>
                        </span>
                        {% render_field f class="form-control form-control-lg pill-right" placeholder=f.label %}
                    </div>
                </div>
                {{ f.errors }}
            {% endfor %}
            <div class="col-md-6 col-10 mx-auto text-right mb-3">
                <a href="#" class="text-decoration-none">Não lembro minha senha</a>
            </div>
            <div class="col-6 mx-auto text-center">
                <div class="d-flex flex-column justify-content-center">
                    <button type="submit" class="btn btn-primary btn-lg rounded-pill">Continuar</button>
                </div>
            </div>
        </form>
    </div>
{% endblock body %}
    

rpg_tracker/core/templates/navbar.html
<!--<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">D&D 5e</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Raças</a></li>
                        <li><a class="dropdown-item" href="#">Classes</a></li>
                        <li><a class="dropdown-item" href="#">Antecedentes</a></li>
                        <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Decks</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Crit - GM</a></li>
                                <li><a class="dropdown-item" href="#">Crit - Players</a></li>
                                <li><a class="dropdown-item" href="#">Fail</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu"><a href="#" class="dropdown-item dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Armadilhas</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Lvl 1-4</a></li>
                                <li><a class="dropdown-item" href="#">Lvl 5-8</a></li>
                                <li><a class="dropdown-item" href="#">Lvl 9-12</a></li>
                                <li><a class="dropdown-item" href="#">Lvl 13-16</a></li>
                                <li><a class="dropdown-item" href="#">Lvl 17-20</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>-->
<nav class="navbar bg-dark navbar-expand-sm navbar-dark bg-light">
    <a class="navbar-brand" href="{% url 'core:home' %}">RPGTracker</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav w-100 d-flex flex-column flex-sm-row">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">CoC 7e</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'coc:skill_list' %}">Skills</a></li>
                        <li><a class="dropdown-item" href="{% url 'coc:ocupation_list' %}">Ocupations</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Harry Potter</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'hp:folio_universitas' %}" class="dropdown-item">Folio Universitas</a></li>
                    </ul>
                </li>
                <div id="profile" class="ml-0 ml-sm-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            {% if user.is_superuser %}
                                <li><a href="/admin" class="dropdown-item">Admin</a></li>
                            {% endif %}
                            <li>
                                <a href="{% url 'accounts:fichas' %}" class="dropdown-item">
                                    {% if user.is_superuser %}
                                        Todas as fichas
                                    {% else %}
                                        Minhas fichas
                                    {% endif %}
                                </a>
                            </li>
                            <li class="nav-item"><a href="{% url 'accounts:user-info' user.pk %}" class="dropdown-item">Meu perfil</a></li>
                            <li class="nav-item"><a href="{% url 'core:logout' %}" class="dropdown-item">Sair</a></li>
                        </ul>
                    </li>
                </div>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'core:login' %}" class="nav-link">Acessar</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>