rpg_tracker/hp/urls.py
from django.urls import path
from . import views

app_name = 'hp'
urlpatterns = [
    path('ficha/<int:pk>', views.ficha, name='ficha'),
    path('ficha/<int:pk>/folio-universitas', views.folio_universitas_ficha, name="folio_universitas_ficha"),
    path('folio-universitas', views.folio_universitas, name="folio_universitas"),
    path('folio-universitas/<int:pk>/cartas', views.folio_universitas_cartas, name="folio_universitas_cartas")
]

rpg_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rpg_tracker.core.urls', namespace='core')),
    path('conta/', include('rpg_tracker.accounts.urls', namespace='accounts')),
    path('coc/', include('rpg_tracker.coc.urls', namespace='coc')),
    path('hp/', include('rpg_tracker.hp.urls', namespace='hp')),
    #path('dnd/', include('rpg_tracker.dnd.urls', namespace='dnd')),
    path('admin/', admin.site.urls),
    path('api/', include('rpg_tracker.api.urls', namespace='api')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

rpg_tracker/hp/models.py
from django.core import validators
from django.db.models.enums import IntegerChoices
from rpg_tracker.core.models import AbstractBaseModel, FichaBase, MesaBase
from django.db import models
from django.urls import reverse

# Create your models here.
class CategoriaFolioUniversitas(AbstractBaseModel):
    nome = models.CharField(verbose_name="Nome", null=False, blank=False, max_length=255)
    imgBase64 = models.TextField(verbose_name="Imagem (Base64)", blank=False, null=False)

    def __str__(self):
        return self.nome

    @property
    def quantidade_cartas(self):
        return self.cartas.count()

    class Meta:
        verbose_name = "categoria Folio Universitas"
        verbose_name_plural = "categorias Folio Universitas"


class CartaFolioUniversitas(AbstractBaseModel):
    nome = models.CharField(verbose_name="Nome", null=False, blank=False, max_length=255)
    categoria = models.ForeignKey(to=CategoriaFolioUniversitas, related_name="cartas", verbose_name="categoria", blank=False, null=False, on_delete=models.CASCADE)
    imgBase64 = models.TextField(verbose_name="Imagem (Base64)", blank=False, null=False)
    descricao = models.TextField(verbose_name="Descrição", blank=False, null=False)
    anoNasc = models.IntegerField(verbose_name="Nascimento", null=True, blank=True)
    anoMort = models.IntegerField(verbose_name="Nascimento", null=True, blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "carta Folio Universitas"
        verbose_name_plural = "cartas Folio Universitas"

class Equipamentos(AbstractBaseModel):
    class TipoMaterial(IntegerChoices):
        LIVRO = 0, "Livro"
        CALDEIRAO = 1, "Caldeirão"
        VASSOURA = 2, "Vassoura"
        VESTES = 3, "Vestes"
        PESSOAIS = 4, "Pessoais"

    nome = models.CharField(verbose_name="Nome", null=False, blank=False, max_length=255)
    material_escolar = models.BooleanField(verbose_name="É material escolar", null=False, blank=False, default=False)

    class Meta:
        verbose_name = 'equipamento'
        verbose_name_plural = 'equipamentos'

class Varinha(AbstractBaseModel):
    class Nucleos(IntegerChoices):
        FENIX = 0, "Pena da cauda de fênix"
        DRAGAO = 1, "Corda de coração de dragão"
        UNICORNIO = 2, "Pelo de unicórnio"
        VEELA = 3, "Cabelo de veela"
        SERPENTE_CHIFRUDA = 4, "Chifre de serpente chifruda dos rios"

    class Madeiras(IntegerChoices):
        BETULA = 0, "Bétula"
        SOVIEIRA = 1, "Sovieira"
        FREIXO = 2, "Freixo"
        AMIEIRO = 3, "Amieiro"
        SABUGUEIRO = 4, "Sabugueiro"
        ABRUNHEIRO =  5, "Abrunheiro"
        CARVALHO = 6, "Carvalho"
        AZEVINHO = 7, "Azevinho"
        AVELA = 8, "Avelã"
        VIDEIRA = 9, "Videira"
        HEDERA = 10, "Hedera"
        SEQUOIA = 11, "Sequoia"

    class Flexibilidade(IntegerChoices):
        DOBRAVEL = 0, "Dobrável"
        SURP_SUAVE = 1, "Surpreendentemente suave"
        SUAVE = 2, "Suave"
        LIG_SUAVE = 3, "Ligeiramente suave"
        BAST_CURVADA = 4, "Bastante curvada"
        MUITO_FLEX = 5, "Muito flexível"
        BAST_FLEX = 6, "Bastante flexível"
        FLEX = 7, "Flexível"
        RAZ_FLEX = 8, "Razoavelmente flexível"
        MALEA = 9, "Maleável"
        FRAGIL = 10, "Frágil"
        ASPERA = 11, "Áspera"
        MACICA = 12, "Maciça"
        VISCOSA = 13, "Viscosa"
        RIGIDA = 14, "Rígida"
        INFLEX = 15, "Inflexível"
        LEV_INFLEX = 16, "Levemente inflexível"
        RESOLUT = 17, "Resoluta"
        MACIA = 18, "Macia"

    nucleo = models.IntegerField(verbose_name="Núcleo", null=False, blank=False, choices=Nucleos.choices)
    madeira = models.IntegerField(verbose_name="Madeira", null=False, blank=False, choices=Madeiras.choices)
    tamanho = models.FloatField(verbose_name="Tamanho", null=False, blank=False)
    flexibilidade = models.IntegerField(verbose_name="Flexibilidade", null=False, blank=False, choices=Flexibilidade.choices)

    def __str__(self):
        return '{0}, {1} centimetros, {2}, núcleo de {3}'.format(self.Madeiras.choices[self.madeira][1], self.tamanho, self.Flexibilidade.choices[self.flexibilidade][1], self.Nucleos.choices[self.nucleo][1])

    class Meta:
        verbose_name = 'varinha'
        verbose_name_plural = 'varinhas'

class FichaHP(FichaBase):
    class CasaHogwarts(IntegerChoices):
        GRIFFINDOR = 0, "Grifinória"
        SLYTHERIN = 1, "Sonserina"
        RAVENCLAW = 2, "Corvinal"
        HUFFLEPUFF = 3, "Lufa-lufa"

    escola = models.CharField(verbose_name="Escola", null=True, blank=True, max_length=255)
    ano_escolar = models.IntegerField(verbose_name="Ano Escolar", null=False, blank=False, default=1, validators=[validators.MinValueValidator(1), validators.MaxValueValidator(7)])
    casa_hogwarts = models.IntegerField(verbose_name="Casa de Hogwarts", null=True, blank=True, choices=CasaHogwarts.choices)
    familiar = models.CharField(verbose_name="Familiar (nome & tipo)", null=True, blank=True, max_length=255)
    atletismo = models.IntegerField(verbose_name="Atletismo", null=False, blank=False, default=0)
    conhecimento = models.IntegerField(verbose_name="Conhecimento", null=False, blank=False, default=0)
    intriga = models.IntegerField(verbose_name="Intriga", null=False, blank=False, default=0)
    magia = models.IntegerField(verbose_name="Magia", null=False, blank=False, default=0)
    varinha = models.ForeignKey(to=Varinha, verbose_name="Varinha", related_name="bruxo", null=True, blank=True, on_delete=models.RESTRICT)

    def save(self, *args, **kwargs):
        self.magia = self.ano_escolar
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return "{0}{1}".format(self.nome_personagem, " ("+self.mesa.name+")" if self.mesa is not None else "")

    def get_absolute_url(self):
        return reverse('hp:ficha', kwargs={'pk': self.pk})

    def get_children(self, skill):
        ret = []
        for x in skill.especializacoes.all():
            per = self.pericias.filter(pericia_id=x.id).filter(ficha__id=self.id).first()
            ret.append({
                'nome' : x.nome,
                'valor' : per.valor if per is not None else 0,
                'children' : self.get_children(x),
                'hint' : ''
            })
        for x in EspecializacoesCustomizadasPlayer.objects.filter(pericia_pai=skill).filter(ficha__id=self.id).all():
            ret.append({
                'nome' : x.nome,
                'valor' : x.valor,
                'children' : [],
                'hint' : x.hint
            })
        return ret

    def get_parents(self, aptidao):
        ret = []
        for x in PericiasEspecializacoes.objects.filter(aptidao=aptidao).all():
            per = self.pericias.filter(pericia_id=x.id).first()
            ret.append({
                'nome' : x.nome,
                'valor' : per.valor if per is not None else 0,
                'children' : self.get_children(x),
                'hint' : ''
            }) 
        return ret

    def get_pericias_atletismo(self):
        return self.get_parents(0)

    def get_pericias_conhecimento(self):
        return self.get_parents(2)

    def get_pericias_intriga(self):
        return self.get_parents(1)

    def get_pericias_magia(self):
        return self.get_parents(3)

    def get_quantidade_cartas_por_categoria(self, categoria):
        return self.cartas.filter(carta__categoria=categoria).count()

    class Meta:
        verbose_name = 'ficha'
        verbose_name_plural = 'fichas'

class CartaFolioUniversitasUsuario(AbstractBaseModel):
    carta = models.ForeignKey(to=CartaFolioUniversitas, null=False, blank=False, related_name='ficha_found', verbose_name='Carta', on_delete=models.RESTRICT)
    ficha = models.ForeignKey(to=FichaHP, null=False, blank=False, related_name="cartas", verbose_name="Ficha", on_delete=models.RESTRICT)

    class Meta:
        verbose_name = 'carta do folio universitas encontrada por ficha'
        verbose_name_plural = 'cartas do folio universitas encontradas por fichas'

class EquipamentoFicha(AbstractBaseModel):
    equip = models.ForeignKey(to=Equipamentos, related_name="fichas", verbose_name="Equipamentos", on_delete=models.RESTRICT, null=False, blank=False)
    ficha = models.ForeignKey(to=FichaHP, related_name="equipamentos", verbose_name="Ficha", on_delete=models.CASCADE, null=False, blank=False)

    class Meta:
        verbose_name = 'equipamento em ficha'
        verbose_name_plural = 'equipamentos em fichas'

class PericiasEspecializacoes(AbstractBaseModel):
    class AptidaoChoices(IntegerChoices):
        ATLETISMO = 0, "Atletismo"
        INTRIGA = 1, "Intriga"
        CONHECIMENTO = 2, "Conhecimento"
        MAGIA = 3, "Magia"
    
    nome = models.CharField(verbose_name="Nome", null=False, blank=False, max_length=255)
    aptidao = models.IntegerField(verbose_name="Aptidão", null=True, blank=True, choices=AptidaoChoices.choices)
    pericia_pai = models.ForeignKey(to='self', related_name='especializacoes', blank=True, null=True, verbose_name='Perícia pai', on_delete=models.RESTRICT)

    def __str__(self) -> str:
        return "{0}{1}{2}".format(self.nome, " ("+str(self.AptidaoChoices.choices[self.aptidao][1])+")" if self.aptidao is not None else "", " - "+str(self.pericia_pai) if self.pericia_pai is not None else "")

    class Meta:
        verbose_name = 'perícia e especialização'
        verbose_name_plural = 'perícias e especializações'

class EspecializacoesCustomizadasPlayer(AbstractBaseModel):
    ficha = models.ForeignKey(to=FichaHP, related_name="especializacoes_custom", blank=False, null=False, verbose_name='Ficha', on_delete=models.RESTRICT)
    nome = models.CharField(verbose_name="Nome", null=False, blank=False, max_length=255)
    pericia_pai = models.ForeignKey(to=PericiasEspecializacoes, related_name='especializacoes_custom', blank=False, null=False, verbose_name='Perícia pai', on_delete=models.RESTRICT)

rpg_tracker/hp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from rpg_tracker.core.decorators import can_see_ficha, only_superuser
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView 
from rpg_tracker.hp import models
# Create your views here.

class FichaDetailView(DetailView):
    model = models.FichaHP
    template_name = 'ficha_hp.html'
    context_object_name = 'ficha'

class FolioUniversitasListView(ListView):
    model = models.CategoriaFolioUniversitas
    template_name = 'folio_universitas.html'
    context_object_name = 'categorias'

    ficha = None

    def get(self, request, *args, **kwargs):
        self.ficha = models.FichaHP.objects.get(pk=kwargs.get('pk')) if kwargs.get('pk') is not None else None
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(FolioUniversitasListView, self).get_context_data(**kwargs)
        ctx['ficha'] = self.ficha
        ctx['qtde_total_cartas'] = models.CartaFolioUniversitas.objects.count()
        return ctx

class FolioUniversitasCartasListView(ListView):
    model = models.CartaFolioUniversitas
    template_name = 'folio_universitas_cartas.html'
    context_object_name = 'cartas'

    categoria = ""

    def get_queryset(self):
        qs = super().get_queryset() 
        return qs.filter(categoria__pk=self.kwargs['pk'])

    def get(self, request, *args, **kwargs):
        self.categoria = get_object_or_404(models.CategoriaFolioUniversitas, pk=kwargs.get('pk'))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx =  super().get_context_data(**kwargs)
        ctx['categoria'] = self.categoria
        return ctx

ficha = login_required(can_see_ficha(FichaDetailView.as_view(), 'hp'))
folio_universitas = login_required(FolioUniversitasListView.as_view())
folio_universitas_ficha = login_required(can_see_ficha(FolioUniversitasListView.as_view(), 'hp'))
folio_universitas_cartas = login_required(FolioUniversitasCartasListView.as_view())

rpg_tracker/hp/templates/ficha_hp.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load hp_tags %}
{% block body %}
    <div class="container-fluid mt-3">
        <div class="row mb-2">
            <div class="col-12 col-sm-10">
                <div class="card h-100">
                    <div class="card-header bg-secondary text-center">
                        <h3 class="card-title mb-0">
                            Características
                        </h3>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p><b>Nome: </b><u>{{ ficha.nome_personagem }}</u></p>
                            <a class="btn btn-primary" href="{% url 'hp:folio_universitas_ficha' ficha.pk %}">Meu Folio Universitas</a>
                        </div>
                        <p><b>Player: </b><u>{{ ficha.jogador }}</u></p>
                        <p><b>Escola: </b><u>{{ ficha.escola|default_if_none:"" }}</u></p>
                        <p><b>Casa: </b><u>{{ ficha.get_casa_hogwarts_display|default_if_none:"" }}</u></p>
                        <div class="d-flex flex-sm-row flex-column mb-3">
                            <b>Ano Escolar: </b>
                            <div class="d-flex flex-row ml-sm-2">
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline1" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 1 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline1">1</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 2 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline2">2</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 3 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline2">3</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 4 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline2">4</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 5 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline2">5</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 6 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline2">6</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" disabled {% if ficha.ano_escolar == 7 %}checked{% endif %}>
                                    <label class="custom-control-label" for="customRadioInline2">7</label>
                                </div>
                            </div>
                        </div>
                        <p><b>Familiar (Nome & tipo): </b><u>{{ ficha.familiar|default_if_none:"" }}</u></p>
                        <p><b>Varinha: </b><u>{{ ficha.varinha|default_if_none:"" }}</u></p>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-2">
                <div class="card h-100">
                    <div class="card-body d-flex align-items-center text-center">
                        <p class="lead mx-auto">Upload de fotos não suportado no momento!</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-12">
                <div class="card h-100">
                    <div class="card-header bg-secondary text-center">
                        <h3 class="card-title mb-0">
                            Aptidões, Perícias e Especializações
                        </h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-sm-3">
                                <div class="col-12 d-flex flex-row">
                                    <h5 class="bg-secondary text-white px-3 mr-1">{{ ficha.atletismo }}</h5>
                                    <h5>Atletismo</h5>
                                </div>
                                {% load_skill_list ficha.get_pericias_atletismo True %}
                            </div>
                            <div class="col-12 col-sm-3">
                                <div class="col-12 d-flex flex-row">
                                    <h5 class="bg-secondary text-white px-3 mr-1">{{ ficha.conhecimento }}</h5>
                                    <h5>Conhecimento</h5>
                                </div>
                                {% load_skill_list ficha.get_pericias_conhecimento True %}
                            </div>
                            <div class="col-12 col-sm-3">
                                <div class="col-12 d-flex flex-row">
                                    <h5 class="bg-secondary text-white px-3 mr-1">{{ ficha.intriga }}</h5>
                                    <h5>Intriga</h5>
                                </div>
                                {% load_skill_list ficha.get_pericias_intriga True %}
                            </div>
                            <div class="col-12 col-sm-3">
                                <div class="col-12 d-flex flex-row">
                                    <h5 class="bg-secondary text-white px-3 mr-1">{{ ficha.magia }}</h5>
                                    <h5>Magia</h5>
                                </div>  
                                {% load_skill_list ficha.get_pericias_magia True %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-12">
                <div class="card h-100">
                    <div class="card-header bg-secondary text-center">
                        <h3 class="card-title mb-0">
                            Equipamentos e materiais escolares
                        </h3>
                    </div>
                    <div class="card-body">
                        {% for item in ficha.equipamentos.all %}
                            {{ item }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

rpg_tracker/hp/templates/folio_universitas.html
{% extends 'base.html' %}
{% load hp_tags %}
{% load static %}
{% block body %}
    <div class="container-fluid mt-3">
        <div class="jumbotron jumbotron-fluid bg-transparent">
            <div class="container text-center">
                <h1 class="display-4">{% if ficha %}Meu Folio Universitas{% else %}Folio Universitas{% endif %}</h1>
                {% if ficha %}
                    <p class="lead">{{ ficha.nome_personagem }}</p>
                    {% if qtde_total_cartas > 0 and qtde_total_cartas > ficha.cartas.count %}
                        {% if not ficha.mesa or not ficha.mesa.open_session or not ficha.in_session %}
                            <a href="#" class="ml-auto btn btn-primary disabled" role="button" aria-disabled="true">
                        {% else %}
                            <a href="#" class="ml-auto btn btn-primary" role="button" aria-disabled="false">
                        {% endif %}Abrir sapo de chocolate</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% for cat in categorias %}
            {% if forloop.first %}
                <div class="d-flex flex-sm-row flex-column justify-content-around flex-wrap">    
            {% endif %}
                {% get_quantidade_cartas_categoria ficha cat as qtde_cartas %}
                <div class="card">
                    <img class="card-img" 
                    {% if not ficha or qtde_cartas > 0 %}
                        src="data:image/png;base64, {{ cat.imgBase64 }}" alt="{{ cat.nome }}"
                    {% else %}    
                        src="{% static 'img/hp_assets/fu_not_found.png' %}" alt="?"
                    {% endif %}
                    >
                    <div class="card-img-overlay d-flex flex-column justify-content-end" style="background: linear-gradient(to bottom, transparent 0%, black 100%);">
                        {% if not ficha or qtde_cartas > 0 %}
                            <h5 class="text-white">{{ cat.nome }}</h5>
                            <small class="text-white">
                                {% if not ficha %}
                                    {{ cat.quantidade_cartas }} cartas
                                {% else %}
                                    {{ qtde_cartas }} de {{ cat.quantidade_cartas }} encontradas
                                {% endif %}
                            </small>
                            <a href="{% url 'hp:folio_universitas_cartas' cat.pk %}" class="stretched-link"></a>
                        {% endif %}
                    </div>
                </div>
            {% if forloop.last %}
                </div>
            {% endif %}
        {% empty %}
            <div class="text-center">
                <p class="lead">Nada encontrado!</p>
            </div>
        {% endfor %}
    </div>
{% endblock body %}

rpg_tracker/hp/templates/folio_universitas_cartas.html
{% extends 'base.html' %}
{% block body %}
    <div class="container-fluid mt-3">
        <div class="jumbotron jumbotron-fluid bg-transparent">
            <div class="container text-center">
                <h1 class="display-4">{% if ficha %}Meu Folio Universitas{% else %}Folio Universitas{% endif %}</h1>
                    <p class="lead">{{ categoria.nome }}</p>
            </div>
        </div>
    </div>
{% endblock %}

rpg_tracker/hp/templates/load_skill_lists.html
{% if skills|length %}
    {% if first %}<div class="col-12">{% endif %}
        <ul {% if first %}class="list-unstyled"{% endif %}>
            {% for skill in skills %}
                <li>
                    <p class="mb-0">
                        {% if skill.valor > 0 %}
                            {{ skill.valor }}
                        {% else %}
                            _
                        {% endif %} - {{ skill.nome }}
                        {% if skill.hint != '' %}
                            <small class="text-muted">({{ skill.hint }})</small>{% endif %}</p>
                    {% include "load_skill_lists.html" with skills=skill.children first=False %}
                </li>
            {% endfor %}
        </ul>
    {% if first %}</div>{% endif %}
{% endif %}