rpg_tracker/dnd/urls.py
from django.urls import path
from. import views
from django.contrib.auth import views as auth_views

app_name = 'dnd'
urlpatterns = [
    path('racas', views.RaceDNDListView.as_view(), name='racas_list'),
    path('racas/<int:pk>', views.RaceDNDDetailView.as_view(), name='racas_details'),
    path('classes', views.ClasseDNDListView.as_view(), name='classes_list'),
    path('classes/<int:pk>', views.ClasseDNDDetailView.as_view(), name='classes_details'),
    path('fichas/<int:pk>', views.ficha_detalhe, name='ficha_detalhe'),
    path('decks/gm_crit', views.get_deck_gm_crit, name='gm_crit_deck'),
    path('decks/player_crit', views.get_deck_player_crit, name='player_crit_deck'),
    path('decks/fail', views.get_deck_fail, name='fail_deck'),
    path('decks/gm_crit/get_card', views.deck_gm_crit_card, name='gm_crit_deck_get_card'),
    path('decks/player_crit/get_card', views.deck_player_crit_card, name='player_crit_deck_get_card'),
    path('decks/fail/get_card', views.deck_fail_card, name='fail_deck_get_card'),
    path('traps/1_4',views.traps_1_4,name='1_4_traps'),
    path('traps/1_4/get',views.traps_1_4_get,name='get_1_4_traps'),
    path('traps/5_8',views.traps_5_8,name='5_8_traps'),
    path('traps/5_8/get',views.traps_5_8_get,name='get_5_8_traps'),
    path('traps/9_12',views.traps_9_12,name='9_12_traps'),
    path('traps/9_12/get',views.traps_9_12_get,name='get_9_12_traps'),
    path('traps/13_16',views.traps_13_16,name='13_16_traps'),
    path('traps/13_16/get',views.traps_13_16_get,name='get_13_16_traps'),
    path('traps/17_20',views.traps_17_20,name='17_20_traps'),
    path('traps/17_20/get',views.traps_17_20_get,name='get_17_20_traps')
]

rpg_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rpg_tracker.core.urls', namespace='core')),
    path('conta/', include('rpg_tracker.accounts.urls', namespace='accounts')),
    path('coc/', include('rpg_tracker.coc.urls', namespace='coc')),
    path('hp/', include('rpg_tracker.hp.urls', namespace='hp')),
    #path('dnd/', include('rpg_tracker.dnd.urls', namespace='dnd')),
    path('admin/', admin.site.urls),
    path('api/', include('rpg_tracker.api.urls', namespace='api')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

rpg_tracker/dnd/forms.py
from django import forms
from .models import ClassesFichaDND

class ClasseFichaDNDDSelectForm(forms.ModelForm):

    class Meta:
        model = ClassesFichaDND
        fields = ['classe','ficha']

rpg_tracker/dnd/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .models import FichaDND, RacesDND, ClasseDND, TrapsDND
from django.views.generic import ListView, DetailView
from django.templatetags.static import static
import json
from random import randint
# Create your views here.

class RaceDNDListView(ListView):
    model = RacesDND
    template_name = 'racas_dnd.html'
    context_object_name = 'racas'

class ClasseDNDListView(ListView):
    model = ClasseDND
    template_name = 'classes_dnd.html'
    context_object_name = 'classes'

class RaceDNDDetailView(DetailView):
    model = RacesDND
    template_name = 'racas_details_dnd.html'
    context_object_name = 'raca'

class ClasseDNDDetailView(DetailView):
    model = ClasseDND
    template_name = 'classes_details_dnd.html'
    context_object_name = 'classe'

def ficha_detalhe(request, pk):
    f = get_object_or_404(FichaDND, pk=pk)
    return render(request, 'ficha_details_dnd.html', {'ficha':f.to_dict()})

def get_deck_gm_crit(request):
    return render(request, 'get_deck.html', {'action':'gm_get_deck', 'loader':static('img/loader.gif')})

def get_deck_player_crit(request):
    return render(request, 'get_deck.html', {'action':'player_get_deck', 'loader':static('img/loader.gif')})

def get_deck_fail(request):
    return render(request, 'get_deck.html', {'action':'fail_get_deck', 'loader':static('img/loader.gif')})


def deck_gm_crit_card(request):
    if request.is_ajax():
        img = static('img/decks/crit_gm/{0}.png'.format(str(randint(1,52))))
        return HttpResponse(json.dumps({'img':img}))
    else:
        return redirect('dnd:gm_crit_deck')

def deck_player_crit_card(request):
    if request.is_ajax():
        img = static('img/decks/crit_player/{0}.png'.format(str(randint(1,52))))
        return HttpResponse(json.dumps({'img':img}))
    else:
        return redirect('dnd:player_crit_deck')

def deck_fail_card(request):
    if request.is_ajax():
        img = static('img/decks/fumble/{0}.png'.format(str(randint(1,52))))
        return HttpResponse(json.dumps({'img':img}))
    else:
        return redirect('dnd:fail_deck')
    
def traps_1_4(request):
    return render(request, 'get_trap.html', {'lvl':'1-4', 'trap_url':reverse('dnd:get_1_4_traps'), 'danger_levels':TrapsDND.DangerKind})

def traps_5_8(request):
    return render(request, 'get_trap.html', {'lvl':'5-8', 'trap_url':reverse('dnd:get_5_8_traps'), 'danger_levels':TrapsDND.DangerKind})

def traps_9_12(request):
    return render(request, 'get_trap.html', {'lvl':'9-12', 'trap_url':reverse('dnd:get_9_12_traps'), 'danger_levels':TrapsDND.DangerKind})

def traps_13_16(request):
    return render(request, 'get_trap.html', {'lvl':'13-16', 'trap_url':reverse('dnd:get_13_16_traps'), 'danger_levels':TrapsDND.DangerKind})

def traps_17_20(request):
    return render(request, 'get_trap.html', {'lvl':'17-20', 'trap_url':reverse('dnd:get_17_20_traps'), 'danger_levels':TrapsDND.DangerKind})

def traps_1_4_get(request):
    if request.is_ajax():
        traps = TrapsDND.objects.filter(level=0).all()
        if 'danger' in request.GET and request.GET.get('danger','') != '':
            traps = traps.filter(danger=request.GET['danger']).all()
        traps = list(traps)
        if len(traps) > 0:
            return HttpResponse(json.dumps(traps[randint(0,len(traps)-1)].to_dict()))
        else:
            return HttpResponse(json.dumps({'err':'Not found!'}))
    else:
        return redirect('dnd:1_4_traps')
    
def traps_5_8_get(request):
    if request.is_ajax():
        traps = TrapsDND.objects.filter(level=1).all()
        if 'danger' in request.GET and request.GET.get('danger','') != '':
            traps = traps.filter(danger=request.GET['danger']).all()
        traps = list(traps)
        if len(traps) > 0:
            return HttpResponse(json.dumps(traps[randint(0,len(traps)-1)].to_dict()))
        else:
            return HttpResponse(json.dumps({'err':'Not found!'}))
    else:
        return redirect('dnd:5_8_traps')

def traps_9_12_get(request):
    if request.is_ajax():
        traps = TrapsDND.objects.filter(level=2).all()
        if 'danger' in request.GET and request.GET.get('danger','') != '':
            traps = traps.filter(danger=request.GET['danger']).all()
        traps = list(traps)
        if len(traps) > 0:
            return HttpResponse(json.dumps(traps[randint(0,len(traps)-1)].to_dict()))
        else:
            return HttpResponse(json.dumps({'err':'Not found!'}))
    else:
        return redirect('dnd:9_12_traps')

def traps_13_16_get(request):
    if request.is_ajax():
        traps = TrapsDND.objects.filter(level=3).all()
        if 'danger' in request.GET and request.GET.get('danger','') != '':
            traps = traps.filter(danger=request.GET['danger']).all()
        traps = list(traps)
        if len(traps) > 0:
            return HttpResponse(json.dumps(traps[randint(0,len(traps)-1)].to_dict()))
        else:
            return HttpResponse(json.dumps({'err':'Not found!'}))
    else:
        return redirect('dnd:13_16_traps')

def traps_17_20_get(request):
    if request.is_ajax():
        traps = TrapsDND.objects.filter(level=4).all()
        if 'danger' in request.GET and request.GET.get('danger','') != '':
            traps = traps.filter(danger=request.GET['danger']).all()
        traps = list(traps)
        if len(traps) > 0:
            return HttpResponse(json.dumps(traps[randint(0,len(traps)-1)].to_dict()))
        else:
            return HttpResponse(json.dumps({'err':'Not found!'}))
    else:
        return redirect('dnd:17_20_traps')

rpg_tracker/dnd/templates/classes_details_dnd.html
{% extends 'base.html' %}


{% block body %}
    {{ classe }}
{% endblock body %}
    

rpg_tracker/dnd/templates/classes_dnd.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
        <div class="text-center">
            <h4 class="display-4">Classes</h4>
        </div>
        {% for classe in classes %}
            {% if forloop.first %}
                <div class="card-columns">
            {% endif %}
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ classe }}</h4>
                    <div class="text-right">
                        <a href="{% url 'dnd:classes_details' classe.pk %}" class="btn btn-success rounded-pill">Ver</a>
                    </div>
                </div>
            </div>
            {% if forloop.last %}
                </div>
            {% endif %}
        {% empty %}
            <div class="text-center">
                <h4 class="display-4">Nada encontrado!</h4>
            </div>
        {% endfor %}
    </div>
{% endblock body %}
    

rpg_tracker/dnd/templates/ficha_details_dnd.html
{% extends 'base.html' %}

{% block body %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-6 text-center">
                <h4>{{ ficha.nome }}</h4>
            </div>
            <div class="col-md-6 ">
                <div class="row">
                    <div class="col-4">
                        <p class="lead mb-0">Classe</p>
                        {% for c in ficha.classes.all %}
                            {% if forloop.first %}
                                <p>
                            {% endif %}
                                {{ c.classe }} {{ c.level }}
                            {% if forloop.last %}
                                </p>
                            {% endif %}
                        {% empty %}
                            <p>N/A</p>
                        {% endfor %}
                    </div>
                    <div class="col-4">
                        <p class="lead mb-0">Antecedentes</p>
                        <p>N/A</p>
                    </div>
                    <div class="col-4">
                        <p class="lead mb-0">Nome do jogador</p>
                        <p>{{ ficha.jogador }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <p class="lead mb-0">Raça</p>
                        <p>{{ ficha.raca.nome }}</p>
                    </div>
                    <div class="col-4">
                        <p class="lead mb-0">Tendência</p>
                        <p>{{ ficha.alinhamento }}</p>
                    </div>
                    <div class="col-4">
                        <p class="lead mb-0">XP</p>
                        <p>{{ ficha.xp }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-2 col-6 text-center">
                <h5>Força</h5>
                {{ ficha.str.value }} ({{ ficha.str.mod }})
            </div>
            <div class="col-md-2 col-6 text-center">
                <h5>Destreza</h5>
                {{ ficha.dex.value }} ({{ ficha.dex.mod }})
            </div>
            <div class="col-md-2 col-6 text-center">
                <h5>Constituição</h5>
                {{ ficha.con.value }} ({{ ficha.con.mod }})
            </div>
            <div class="col-md-2 col-6 text-center">
                <h5>Inteligência</h5>
                {{ ficha.int.value }} ({{ ficha.int.mod }})
            </div>
            <div class="col-md-2 col-6 text-center">
                <h5>Sabedoria</h5>
                {{ ficha.wis.value }} ({{ ficha.wis.mod }})
            </div>
            <div class="col-md-2 col-6 text-center">
                <h5>Carisma</h5>
                {{ ficha.cha.value }} ({{ ficha.cha.mod }})
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4 text-md-left text-center">
                <h2>Testes de resistência</h2>
                <div class="custom-control custom-checkbox pb-2">
                    <input type="checkbox" class="custom-control-input" name="str_per" 
                    {% if ficha.str.saving %}
                        checked
                    {% endif %}
                    > 
                    <label class="custom-control-label" for="str_per"><ins>{{ ficha.str.saving_value }}</ins> Força</label>
                </div>
                <div class="custom-control custom-checkbox pb-2">
                    <input type="checkbox" class="custom-control-input" name="dex_per"
                    {% if ficha.dex.saving %}
                        checked
                    {% endif %}
                    >
                    <label class="custom-control-label" for="dex_per"><ins>{{ ficha.dex.saving_value }}</ins> Destreza</label>
                </div>
                <div class="custom-control custom-checkbox pb-2">
                    <input type="checkbox" class="custom-control-input" name="con_per"
                    {% if ficha.con.saving %}
                        checked
                    {% endif %}
                    >
                    <label class="custom-control-label" for="con_per"><ins>{{ ficha.con.saving_value }}</ins> Constituição</label>
                </div>
                <div class="custom-control custom-checkbox pb-2">
                    <input type="checkbox" class="custom-control-input" name="int_per"
                    {% if ficha.int.saving %}
                        checked
                    {% endif %}
                    >
                    <label class="custom-control-label" for="int_per"><ins>{{ ficha.int.saving_value }}</ins> Inteligência</label>
                </div>
                <div class="custom-control custom-checkbox pb-2">
                    <input type="checkbox" class="custom-control-input" name="wis_per"
                    {% if ficha.wis.saving %}
                        checked
                    {% endif %}
                    >
                    <label class="custom-control-label" for="wis_per"><ins>{{ ficha.wis.saving_value }}</ins> Sabedoria</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" name="cha_per"
                    {% if ficha.cha.saving %}
                        checked
                    {% endif %}
                    >
                    <label class="custom-control-label" for="cha_per"><ins>{{ ficha.cha.saving_value }}</ins> Carisma</label>
                </div>
            </div>
            <div class="col-md-8 text-center text-md-left mt-md-0 mt-3">
                <h2>Perícias</h2>
                <div class="card-columns">
                    {% for s in ficha.skills %}
                        <div class="card bg-transparent border-0">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" name="per_{{ s.ident }}" {% if s.has_skill %}checked{% endif %}>
                                <label class="custom-control-label" for="per_{{ s.ident }}"><ins>{{ s.value }}</ins> {{ s.text }} <small class="text-muted">({{ s.use }})</small></label>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 text-center text-md-left mt-3">
                <h2>Idiomas e outras proficiências</h2>
                <p><strong>Idiomas: </strong>
                {% for i in ficha.raca.idiomas.all %}
                    {{ i }}{% if not forloop.last %},{% endif %}
                {% endfor %}</p>
                <p>+todo</p>
            </div>
            <div class="col-md-4 text-center text-md-left mt-3">
                <h2>Traços</h2>
                <div id="accordion">
                    {% for t in ficha.tracos.all %}
                        <div class="card">
                            <div class="card-header" id="H-{{ t.name_trim }}">
                                <h5 class="mb-0">
                                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#B-{{ t.name_trim }}" aria-expanded="false" aria-controls="B-{{ t.name }}">
                                        {{ t.name }}
                                    </button>
                                </h5>
                            </div>
                        </div>
                        <div class="card">
                            <div id="B-{{ t.name_trim }}" class="collapse" aria-labelledby="H-{{ t.name_trim }}" data-parent="#accordion">
                                <div class="card-body">
                                    {{ t.description }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

rpg_tracker/dnd/templates/get_deck.html
{% extends 'base.html' %}
{% load static %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function(){
            pick_card();
            $("#new_card").on("click", function(e){
                $("#img_load").attr('src', $("#img_load").data('img_loader'));
                pick_card();
            });
        });
        function pick_card(){
            $.ajax({
                type : 'GET',
                url : $("#img_load").data('img_get_url'),
                dataType : 'json'
            }).done(function(data, textStatus, jqXHR){
                $("#img_load").attr('src', data.img)
            }).fail(function(jqXHR, status, error){
                console.log(error)
            });
        }
    </script>
{% endblock js %}

{% block body %}
    <div class="container justify-content-center text-center mt-3">
        <button id="new_card" class="btn btn-success mb-3">Pegar outra carta</button>
        <br>
        <img src="{% static '/img/loader.gif' %}" alt="Deck card" class="img-fluid mt-auto w-50" id="img_load" data-img_get_url="
        {% if action == 'gm_get_deck' %}
            {% url 'dnd:gm_crit_deck_get_card' %}
        {% elif action == 'fail_get_deck' %}
            {% url 'dnd:fail_deck_get_card' %}
        {% else %}
            {% url 'dnd:player_crit_deck_get_card' %}
        {% endif %}" data-img_loader='{{ loader }}'>
    </div>    
{% endblock body %}
    

rpg_tracker/dnd/templates/get_trap.html
{% extends 'base.html' %}
{% load static %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function(){
            pick_trap();
            $("#new_trap").on("click", function(e){
                pick_trap();
                e.preventDefault();
            });
        });
        function pick_trap(){
            $("#img_load").show();
            $.ajax({
                type : 'GET',
                url : $("#tbl_trap").data('get_trap_url'),
                data : {
                    danger : $("#danger").children("option:selected").val()
                },
                dataType : 'json'
            }).done(function(data, textStatus, jqXHR){
                var table = $("#tbl_trap");
                table.empty();
                if(data.err){
                    alert('Nada encontrado!');
                    $("#img_load").hide();
                    return
                }
                table.append("<thead><tr><th colspan=2>"+data.name+" <small>("+data.kind+", "+data.danger+")<p class='mb-0'>"+data.description+"</p></small></th></tr></thead>");
                table.append("<tbody>"+
                                "<tr>"+
                                    "<th scope='row'>Gatilho ("+data.trigger.kind+")</th>"+
                                    "<td>"+data.trigger.description+"</td>"+
                                "</tr>"+
                                "<tr>"+
                                    "<th scope='row'>Effeito ("+data.effect.kind+")</th>"+
                                    "<td>"+data.effect.description+"</td>"+
                                "</tr>"+
                                "<tr>"+
                                    "<th scope='row'>Contramedidas</th>"+
                                    "<td>"+data.countermeasures+"</td>"+
                                "</tr>"+
                             "</tbody>");
                $("#img_load").hide();
                console.log(data);
            }).fail(function(jqXHR, status, error){
                console.log(error)
            });
        }
    </script>
{% endblock js %}

{% block body %}
    <div class="container justify-content-center text-center mt-3">
        <div class="row text-left d-flex justify-content-center">
            <div class="form-group col-4">
                <label for="danger" class="mb-0"><small>Tipo de perigo</small></label>
            {% for v, t in danger_levels.choices %}
                {% if forloop.first %}
                    <select class="form-control" name="danger" id="danger">
                        <option value="" selected>Todos</option>
                {% endif %}
                <option value="{{ v }}">{{ t }}</option>
                {% if forloop.last %}
                    </select>
                {% endif %}
            {% endfor %}
            </div>
        </div>
        <button id="new_trap" class="btn btn-success mb-3">Pegar outra armadilha</button>
        <br>
        <img src="{% static '/img/loader.gif' %}" alt="Loader" class="img-fluid mt-auto w-50" id="img_load">
        <table class="table table-bordered" id="tbl_trap" data-get_trap_url="{{ trap_url }}"></table>
    </div>    
{% endblock body %}
    

rpg_tracker/dnd/templates/racas.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
        <div class="text-center">
            <h4 class="display-4">Raças</h4>
        </div>
        {% for raca in racas %}
            {% if forloop.first %}
                <div class="card-columns">
            {% endif %}
            <div class="card">
                <img class="card-img-top" src="holder.js/100x180/" alt="">
                <div class="card-body">
                    <h4 class="card-title">{{ raca }}</h4>
                    <div class="text-right">
                        <a href="{% url 'dnd:racas_details' raca.pk %}" class="btn btn-success rounded-pill">Ver</a>
                    </div>
                </div>
            </div>
            {% if forloop.last %}
                </div>
            {% endif %}
        {% empty %}
            <div class="text-center">
                <h4 class="display-4">Nada encontrado!</h4>
            </div>
        {% endfor %}
    </div>
{% endblock body %}
    

rpg_tracker/dnd/templates/racas_details.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid bg-transparent mb-0">
            <div class="container">
                <h1 class="display-3">{{ raca}}</h1>
                <p class="lead">{{ raca.race_desc }}</p>
            </div>
        </div>
        <div class="text-center">
            <h2 class="display-4">Incrementos de habilidade</h2>
            <div class="row">
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Força</p>
                    <p>{{ raca.str_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Destreza</p>
                    <p>{{ raca.dex_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Constituição</p>
                    <p>{{ raca.con_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Inteligência</p>
                    <p>{{ raca.int_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Sabedoria</p>
                    <p>{{ raca.wis_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Carisma</p>
                    <p>{{ raca.cha_inc }}</p>
                </div>
            </div>
            <!-- <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Força</th>
                            <th>Destreza</th>
                            <th>Constituição</th>
                            <th>Inteligência</th>
                            <th>Sabedoria</th>
                            <th>Carisma</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div> -->
        </div>
    </div>
{% endblock body %}
    

rpg_tracker/dnd/templates/racas_details_dnd.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid bg-transparent mb-0">
            <div class="container">
                <h1 class="display-3">{{ raca.race_name }}</h1>
                <p class="lead">{{ raca.race_desc }}</p>
            </div>
        </div>
        <div class="text-center">
            <h2 class="display-4">Incrementos de habilidade</h2>
            <div class="row">
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Força</p>
                    <p>{{ raca.str_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Destreza</p>
                    <p>{{ raca.dex_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Constituição</p>
                    <p>{{ raca.con_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Inteligência</p>
                    <p>{{ raca.int_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Sabedoria</p>
                    <p>{{ raca.wis_inc }}</p>
                </div>
                <div class="col-md-2 col-4">
                    <p class="mb-0 lead">Carisma</p>
                    <p>{{ raca.cha_inc }}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="text-center">
                <h2 class="display-4">Traços</h2>
                {% for t in raca.traits.all %}
                    {% if forloop.first %}
                        <div class="card-columns">
                    {% endif %}
                    
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{{ t.name }}</h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ t.description }}</p>
                        </div>
                    </div>

                    {% if forloop.last and forloop.count > 0 %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}
    

rpg_tracker/dnd/templates/racas_dnd.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
        <div class="text-center">
            <h4 class="display-4">Raças</h4>
        </div>
        {% for raca in racas %}
            {% if forloop.first %}
                <div class="card-columns">
            {% endif %}
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ raca }}</h4>
                    <div class="text-right">
                        <a href="{% url 'dnd:racas_details' raca.pk %}" class="btn btn-success rounded-pill">Ver</a>
                    </div>
                </div>
            </div>
            {% if forloop.last %}
                </div>
            {% endif %}
        {% empty %}
            <div class="text-center">
                <h4 class="display-4">Nada encontrado!</h4>
            </div>
        {% endfor %}
    </div>
{% endblock body %}
    